heartbeat.config.monitors:
  path: ${path.config}/monitors.d/*.yml
  reload.enabled: false
  reload.period: 5s

heartbeat.monitors:
  - type: http
    id: "wordpress_frontend"
    name: "WordPress Frontend"
    schedule: '@every 10s'
    hosts: ["http://192.168.81.129/"]
    check.response:
      status: 200-399
  - type: tcp
    id: "mysql_port"
    name: "MySQL Port"
    schedule: '@every 10s'
    hosts: ["192.168.81.129:3306"]

setup.template.settings:
  index.number_of_shards: 1
  index.codec: best_compression

setup.kibana:
output.elasticsearch:

  hosts: ["192.168.81.153:9200"]
.
  preset: balanced

processors:
  - add_observer_metadata:

