  GNU nano 4.8                          /etc/logstash/conf.d/filebeat.conf                                    
input {
  beats {
    port => 5044
  }
}
filter {
  if [fileset][module] == "nginx" {
    grok {
      match => { "message" => "%{NGINX_ACCESSLOG}" }
    }
    date {
      match => [ "timestamp", "dd/MMM/YYYY:HH:mm:ss Z" ]
    }
  }

  if [fileset][module] == "mysql" {
    grok {
      match => { "message" => "%{MYSQL_GENERAL_LOG}" }
    }
    date {
      match => [ "timestamp", "yyyy-MM-dd HH:mm:ss" ]
    }
  }
  if [fileset][module] == "php-fpm" {
    grok {
      match => { "message" => "%{PHP_FPM_ERROR}" }
    }
    date {
      match => [ "timestamp", "yyyy-MM-dd HH:mm:ss" ]
    }
  }
}
output {
  elasticsearch {
    hosts => ["http://localhost:9200"]
    index => "logstash-%{+YYYY.MM.dd}"
  }
}

