data_dir: "/var/lib/vector"
sources:
  log_files:
    type: file
    include:
      - "/var/log/nginx/*.log"
      - "/var/log/mysql/*.log"
      - "/var/log/php*.log"
    ignore_older: 86400
    read_from: "end"
    fingerprint:
      strategy: "checksum"

transforms:
  log_parser:
    type: remap
    inputs:
      - log_files
    source: |-
      if includes!(.file, "nginx") {
        .parsed = parse_grok!(.message, "%{COMBINEDAPACHELOG}")
        if exists(.parsed.timestamp) {
          .timestamp = parse_timestamp!(
            .parsed.timestamp,
            "%d/%b/%Y:%H:%M:%S %z"
          )
        }

      } else if includes!(.file, "mysql") {
        .parsed = parse_grok!(
          .message,
          "%{TIMESTAMP_ISO8601:mysql_ts} %{NUMBER:thread_id} \\[%{LOGLEVEL:log_level}\\] \\[%{DATA:code}\\] %>
        )
        if exists(.parsed.mysql_ts) {
          .timestamp = parse_timestamp!(
            .parsed.mysql_ts,
            "%Y-%m-%dT%H:%M:%S.%fZ"
          )
        }

      } else if includes!(.file, "php") {
        .parsed = parse_grok!(
          .message,
          "\\[%{DATA:php_date} %{TIME:php_time}\\] %{LOGLEVEL:php_level}: \\[pool %{WORD:php_pool}\\] child %>
        )

        if is_string(.parsed.php_date) && is_string(.parsed.php_time) {
                   .php_datetime, err = (.parsed.php_date + " " + .parsed.php_time)

          if err != null {
            .php_ts_error = err
          } else {
            .timestamp, parse_err = parse_timestamp(.php_datetime, "%d-%b-%Y %H:%M:%S")
            if parse_err != null {
              .php_ts_error = parse_err
            }
          }
        } else {
          .php_ts_error = "Fields .php_date or .php_time are missing or not strings"
        }

      } else {
        .unparsed = true
      }

sinks:
  elasticsearch:
    type: elasticsearch
    inputs:
      - log_parser
    endpoints:
      - "http://192.168.81.153:9200"
    mode: bulk
    bulk:
      index: "vector-logs-%Y.%m.%d"

