[server]
  bind-address = ":8888"
  log-level = "info"
[logging]
  level = "info"
  file = "/var/log/chronograf/chronograf.log"
[auth]
  disable = true
[dashboard]
  time-zone = "UTC"
[http]
  enabled = true
  bind-address = ":8888"
  pprof-enabled = false
