[meta]
  dir = "/var/lib/influxdb/meta"
  retention-autocreate = true

[data]
  dir = "/var/lib/influxdb/data"
  wal-dir = "/var/lib/influxdb/wal"
  query-timeout = "30s"
  max-concurrent-queries = 0
  max-select-point = 0
  max-select-series = 0

[http]
  enabled = true
  bind-address = ":8086"
  auth-enabled = false
  log-enabled = true
  write-tracing = false
  pprof-enabled = false
  flux-enabled = true

[logging]
  level = "info"
  file = "/var/log/influxdb/influxd.log"

[monitor]
  store-enabled = true
  store-database = "_internal"
