[default]
  hostname = "kapacitor"
[[influxdb]]
  urls = ["http://influxdb:8086"]
  username = "admin"
  password = "adminpassword"
  database = "telegraf"
[http]
  enabled = true
  bind-address = ":9092"
  auth-enabled = false
  pprof-enabled = false
[logging]
  level = "info"
  file = "/var/log/kapacitor/kapacitor.log"
