[global_tags]
  customer = "OTUSTASK"
  os = "linux"

[agent]
  interval = "10s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "10s"
  flush_jitter = "0s"
  precision = ""
[[outputs.influxdb]]
  urls = ["http://influxdb:8086"]
  database = "telegraf"

[[inputs.nginx]]
  urls = ["http://nginx:8080/stub_status"]

[[inputs.mysql]]
  servers = ["myuser:1234@tcp(mysql:3306)/"]

[[inputs.phpfpm]]
  urls = ["http://wordpress:9000/status"]
